doctrine:
    dbal:
        driver: 'pdo_pgsql'
        server_version: '11.2'
        charset: utf8
        url: '%env(resolve:DATABASE_URL)%'
        default_table_options:
            charset: utf8
            collate: '-'
        types:
            user_user_id: 'App\Model\User\Entity\User\IdType'
            user_user_email: 'App\Model\User\Entity\User\EmailType'
            user_user_role: 'App\Model\User\Entity\User\RoleType'
            post_post_id: 'App\Model\Post\Entity\Post\IdType'
            post_post_author_id: 'App\Model\Post\Entity\Post\AuthorIdType'
            post_post_status: 'App\Model\Post\Entity\Post\StatusType'
            like_like_id: 'App\Model\Like\Entity\Like\IdType'
            like_like_author_id: 'App\Model\Like\Entity\Like\AuthorIdType'
            comment_comment_id: 'App\Model\Comment\Entity\Comment\IdType'
            comment_comment_author_id: 'App\Model\Comment\Entity\Comment\AuthorIdType'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            User:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Model/User/Entity'
                prefix: 'App\Model\User\Entity'
                alias: User
            Post:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Model/Post/Entity'
                prefix: 'App\Model\Post\Entity'
                alias: Post
            Like:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Model/Like/Entity'
                prefix: 'App\Model\Like\Entity'
                alias: Like
            Comment:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Model/Comment/Entity'
                prefix: 'App\Model\Comment\Entity'
                alias: Comment
